import { User } from "@/components/pages/profilePages/types";

export const testGuestUserProfile: User = {
  id: "johnsmith-032026",
  userAvaterUrl: "",
  userName: "JohnSmith",
  fullName: "John Smith",
  userLevel: "guest",
  email: "john@email.com",
  memberSince: "Mar 2026",
  phoneNumber: "+1 (555) 000-1111",
  totalSpentByUser: "$51,890",
  rentals: [
    {
      id: "SR-2026-0043",
      rentId: "SR-2026-0043",
      status: "Upcoming",
      hostRatingForGuest: "",
      pickUpDate: "Mar 14, 2026",
      returnDate: "Mar 17, 2026",
      pickupLocation: "Downtown Office",
      price: "$255",
      tripDurationDays: "3 days",
      tripCost: "$1,785",
      totalPaid: "$1,900",
      pickupStreet: "123 Main Street",
      pickupCity: "Austin",
      rentalRate: {
        daily: 770,
        weekly: 4900,
        monthly: 18500,
      },
      car: {
        carId: "urbanRentalsUK-toyotaCamry-012024",
        imageUrl: "/images/toyota-camry-2024.webp",
        carName: "Toyota Camry",
        carType: "Sedan",
        manufactureYear: 2024,
        plateNumber: "JYB 8358",
        features: [
          "Air Conditioning",
          "GPS Navigator",
          "Child Seat",
          "Bluetooth",
          "Backup Camera",
        ],
      },
      host: {
        hostId: "urbanRentalsUK-012025",
        hostName: "Urban Rentals UK",
        hostSlug: "/host/metro-car-rentals",
        contactNumber: "555-123-4567",
      },
    },
    {
      id: "SR-2026-0040",
      rentId: "SR-2026-0040",
      status: "Active",
      hostRatingForGuest: "",
      pickUpDate: "Mar 10, 2026",
      returnDate: "Mar 17, 2026",
      pickupLocation: "Downtown Office",
      price: "$112.50",
      tripDurationDays: "7 days",
      tripCost: "$787.5",
      totalPaid: "$1,900",
      car: {
        carId: "metroCarRentals-toyotaCamry-012024",
        imageUrl: "/images/porsche-macan-2019.webp",
        carName: "Porsche Macan",
        carType: "SUV",
        manufactureYear: 2019,
        plateNumber: "DMN 403",
        features: [
          "Air Conditioning",
          "GPS Navigator",
          "Child Seat",
          "Sunroof",
          "Bluetooth",
          "Backup Camera",
          "Wireless Charging",
          "360 Camera View",
        ],
      },
      host: {
        hostId: "metroCarRentals-012025",
        hostName: "Metro Car Rentals",
        hostSlug: "/host/metro-car-rentals",
        contactNumber: "555-123-4567",
      },
    },
    {
      id: "SR-2026-0032",
      rentId: "SR-2026-0032",
      status: "Completed",
      hostRatingForGuest: 4,
      pickUpDate: "Feb 20, 2026",
      returnDate: "Feb 24, 2026",
      pickupLocation: "Downtown Office",
      price: "$180.00",
      tripDurationDays: "4 days",
      tripCost: "$720",
      totalPaid: "$900",
      car: {
        carId: "coastalCarSharing-toyotaCamry-012024",
        imageUrl: "/images/lexus-lx-570-2021.webp",
        carName: "Lexus LX 570",
        carType: "SUV",
        manufactureYear: 2021,
        plateNumber: "JYB 8358",
        features: [
          "Air Conditioning",
          "GPS Navigator",
          "Child Seat",
          "Sunroof",
          "Bluetooth",
          "Backup Camera",
          "Wireless Charging",
          "360 Camera View",
        ],
      },
      host: {
        hostId: "coastalCarSharing-012025",
        hostName: "Coastal Car Sharing",
        hostSlug: "/host/coastal-car-sharing",
        contactNumber: "555-123-4567",
      },
    },
    {
      id: "SR-2026-0039",
      rentId: "SR-2026-0039",
      status: "Cancelled",
      hostRatingForGuest: "",
      pickUpDate: "Jan 8, 2026",
      returnDate: "Jan 10, 2026",
      pickupLocation: "Downtown Office",
      price: "$190.00",
      tripDurationDays: "2 days",
      tripCost: "$380",
      totalPaid: "$500",
      car: {
        carId: "nordicVentures-toyotaCamry-012024",
        imageUrl: "/images/mercedes-s500-2025.webp",
        carName: "Mercedes S500",
        carType: "Sedan",
        manufactureYear: 2025,
        plateNumber: "RDT 996",
        features: [
          "Air Conditioning",
          "GPS Navigator",
          "Child Seat",
          "Sunroof",
          "Bluetooth",
          "Backup Camera",
          "Wireless Charging",
          "360 Camera View",
        ],
      },
      host: {
        hostId: "nordicVentures-012025",
        hostName: "Nordic Ventures",
        hostSlug: "/host/nordic-ventures",
        contactNumber: "555-123-4567",
      },
    },
    {
      id: "SR-2026-0042",
      rentId: "SR-2026-0042",
      status: "Upcoming",
      hostRatingForGuest: "",
      pickUpDate: "Mar 14, 2026",
      returnDate: "Mar 17, 2026",
      pickupLocation: "Downtown Office",
      price: "$255.00",
      tripDurationDays: "3 days",
      tripCost: "$1,785",
      totalPaid: "$1,900",
      pickupStreet: "123 Main Street",
      pickupCity: "Austin",
      rentalRate: {
        daily: 770,
        weekly: 4900,
        monthly: 18500,
      },
      car: {
        carId: "urbanRentalsUK-toyotaCamry-012024",
        imageUrl: "/images/toyota-camry-2024.webp",
        carName: "Toyota Camry",
        carType: "Sedan",
        manufactureYear: 2024,
        plateNumber: "JYB 8358",
        features: [
          "Air Conditioning",
          "GPS Navigator",
          "Child Seat",
          "Sunroof",
          "Bluetooth",
          "Backup Camera",
          "Wireless Charging",
          "360 Camera View",
        ],
      },
      host: {
        hostId: "urbanRentalsUK-012025",
        hostName: "Urban Rentals UK",
        hostSlug: "/host/metro-car-rentals",
        contactNumber: "555-123-4567",
      },
    },
    {
      id: "SR-2026-0069",
      rentId: "SR-2026-0069",
      status: "Active",
      hostRatingForGuest: "",
      pickUpDate: "Mar 10, 2026",
      returnDate: "Mar 17, 2026",
      pickupLocation: "Downtown Office",
      price: "$112.50",
      tripDurationDays: "7 days",
      tripCost: "$787.5",
      totalPaid: "$900",
      car: {
        carId: "metroCarRentals-toyotaCamry-012024",
        imageUrl: "/images/porsche-macan-2019.webp",
        carName: "Porsche Macan",
        carType: "SUV",
        manufactureYear: 2019,
        plateNumber: "DMN 403",
        features: [
          "Air Conditioning",
          "GPS Navigator",
          "Child Seat",
          "Sunroof",
          "Bluetooth",
          "Backup Camera",
          "Wireless Charging",
          "360 Camera View",
        ],
      },
      host: {
        hostId: "metroCarRentals-012025",
        hostName: "Metro Car Rentals",
        hostSlug: "/host/metro-car-rentals",
        contactNumber: "555-123-4567",
      },
    },
    {
      id: "SR-2026-0031",
      rentId: "SR-2026-0031",
      status: "Completed",
      hostRatingForGuest: 4,
      pickUpDate: "Feb 20, 2026",
      returnDate: "Feb 24, 2026",
      pickupLocation: "Downtown Office",
      price: "$180.00",
      tripDurationDays: "4 days",
      tripCost: "$1,785",
      totalPaid: "$1,900",
      car: {
        carId: "coastalCarSharing-toyotaCamry-012024",
        imageUrl: "/images/lexus-lx-570-2021.webp",
        carName: "Lexus LX 570",
        carType: "SUV",
        manufactureYear: 2021,
        plateNumber: "JYB 8358",
        features: [
          "Air Conditioning",
          "GPS Navigator",
          "Child Seat",
          "Sunroof",
          "Bluetooth",
          "Backup Camera",
          "Wireless Charging",
          "360 Camera View",
        ],
      },
      host: {
        hostId: "coastalCarSharing-012025",
        hostName: "Coastal Car Sharing",
        hostSlug: "/host/coastal-car-sharing",
        contactNumber: "555-123-4567",
      },
    },
    {
      id: "SR-2026-0038",
      rentId: "SR-2026-0038",
      status: "Cancelled",
      hostRatingForGuest: "",
      pickUpDate: "Jan 8, 2026",
      returnDate: "Jan 10, 2026",
      pickupLocation: "Downtown Office",
      price: "$190.00",
      tripDurationDays: "2 days",
      tripCost: "$1,785",
      totalPaid: "$1,900",
      car: {
        carId: "nordicVentures-toyotaCamry-012024",
        imageUrl: "/images/mercedes-s500-2025.webp",
        carName: "Mercedes S500",
        carType: "Sedan",
        manufactureYear: 2025,
        plateNumber: "RDT 996",
        features: [
          "Air Conditioning",
          "GPS Navigator",
          "Child Seat",
          "Sunroof",
          "Bluetooth",
          "Backup Camera",
          "Wireless Charging",
          "360 Camera View",
        ],
      },
      host: {
        hostId: "nordicVentures-012025",
        hostName: "Nordic Ventures",
        hostSlug: "/host/nordic-ventures",
        contactNumber: "555-123-4567",
      },
    },
  ],
};

export const rentals = [
  {
    rentId: "SR-2026-0043",
    hostId: "urbanRentalsUK-012025",
    carId: "urbanRentalsUK-toyotaCamry-012024",
    pickUpDate: "Mar 14, 2026",
    returnDate: "Mar 17, 2026",
    price: 255.0,
    status: "Upcoming",
    hostRatingForGuest: "",
    guestRatingForHost: "",
    guestComments: [
      {
        userId: "johnsmith-032026",
        userType: "Guest",
        post: "The car was very good and well maintained",
        dateCreated: "Mar 17, 2026",
      },
      {
        userId: "johnsmith-032026",
        userType: "Host",
        post: "The car was in a very good condition when it was returned",
        dateCreated: "Mar 17, 2026",
      },
    ],
    hostComments: [],
  },
  {
    rentId: "SR-2026-0040",
    hostId: "metroCarRentals-012025",
    carId: "metroCarRentals-toyotaCamry-012024",
    pickUpDate: "Mar 10, 2026",
    returnDate: "Mar 17, 2026",
    price: 11.5,
    status: "Active",
    hostRatingForGuest: "",
    guestRatingForHost: "",
    guestComments: [
      {
        userId: "johnsmith-032026",
        userType: "Guest",
        post: "The car was very good and well maintained",
        dateCreated: "Mar 17, 2026",
      },
      {
        userId: "johnsmith-032026",
        userType: "Host",
        post: "The car was in a very good condition when it was returned",
        dateCreated: "Mar 17, 2026",
      },
    ],
    hostComments: [],
  },
  {
    rentId: "SR-2026-0032",
    hostId: "coastalCarSharing-012025",
    carId: "coastalCarSharing-toyotaCamry-012024",
    pickUpDate: "Feb 20, 2026",
    returnDate: "Feb 24, 2026",
    price: 780.0,
    status: "Completed",
    hostRatingForGuest: 4,
    guestRatingForHost: 4,
    guestComments: [
      {
        userId: "johnsmith-032026",
        userType: "Guest",
        post: "The car was very good and well maintained",
        dateCreated: "Mar 17, 2026",
      },
      {
        userId: "johnsmith-032026",
        userType: "Host",
        post: "The car was in a very good condition when it was returned",
        dateCreated: "Mar 17, 2026",
      },
    ],
    hostComments: [],
  },
  {
    rentId: "SR-2026-0039",
    hostId: "nordicVentures-012025",
    carId: "nordicVentures-toyotaCamry-012024",
    pickUpDate: "Jan 8, 2026",
    returnDate: "Jan 10, 2026",
    price: 130.0,
    status: "Cancelled",
    hostRatingForGuest: "",
    guestRatingForHost: "",
    guestComments: [
      {
        userId: "johnsmith-032026",
        userType: "Guest",
        post: "The car was very good and well maintained",
        dateCreated: "Mar 17, 2026",
      },
      {
        userId: "johnsmith-032026",
        userType: "Host",
        post: "The car was in a very good condition when it was returned",
        dateCreated: "Mar 17, 2026",
      },
    ],
    hostComments: [],
  },
  {
    rentId: "SR-2026-0042",
    hostId: "urbanRentalsUK-012025",
    carId: "urbanRentalsUK-toyotaCamry-012024",
    pickUpDate: "Mar 14, 2026",
    returnDate: "Mar 17, 2026",
    price: 255.0,
    status: "Upcoming",
    hostRatingForGuest: "",
    guestRatingForHost: "",
    guestComments: [
      {
        userId: "johnsmith-032026",
        userType: "Guest",
        post: "The car was very good and well maintained",
        dateCreated: "Mar 17, 2026",
      },
      {
        userId: "johnsmith-032026",
        userType: "Host",
        post: "The car was in a very good condition when it was returned",
        dateCreated: "Mar 17, 2026",
      },
    ],
    hostComments: [],
  },
  {
    rentId: "SR-2026-0039",
    hostId: "metroCarRentals-012025",
    carId: "metroCarRentals-toyotaCamry-012024",
    pickUpDate: "Mar 10, 2026",
    returnDate: "Mar 17, 2026",
    price: 11.5,
    status: "Active",
    hostRatingForGuest: "",
    guestRatingForHost: "",
    guestComments: [
      {
        userId: "johnsmith-032026",
        userType: "Guest",
        post: "The car was very good and well maintained",
        dateCreated: "Mar 17, 2026",
      },
      {
        userId: "johnsmith-032026",
        userType: "Host",
        post: "The car was in a very good condition when it was returned",
        dateCreated: "Mar 17, 2026",
      },
    ],
    hostComments: [],
  },
  {
    rentId: "SR-2026-0031",
    hostId: "coastalCarSharing-012025",
    carId: "coastalCarSharing-toyotaCamry-012024",
    pickUpDate: "Feb 20, 2026",
    returnDate: "Feb 24, 2026",
    price: 780.0,
    status: "Completed",
    hostRatingForGuest: 4,
    guestRatingForHost: 4,
    guestComments: [
      {
        userId: "johnsmith-032026",
        userType: "Guest",
        post: "The car was very good and well maintained",
        dateCreated: "Mar 17, 2026",
      },
      {
        userId: "johnsmith-032026",
        userType: "Host",
        post: "The car was in a very good condition when it was returned",
        dateCreated: "Mar 17, 2026",
      },
    ],
    hostComments: [],
  },
  {
    rentId: "SR-2026-0038",
    hostId: "nordicVentures-012025",
    carId: "nordicVentures-toyotaCamry-012024",
    pickUpDate: "Jan 8, 2026",
    returnDate: "Jan 10, 2026",
    price: 130.0,
    status: "Cancelled",
    hostRatingForGuest: "",
    guestRatingForHost: "",
    guestComments: [
      {
        userId: "johnsmith-032026",
        userType: "Guest",
        post: "The car was very good and well maintained",
        dateCreated: "Mar 17, 2026",
      },
      {
        userId: "johnsmith-032026",
        userType: "Host",
        post: "The car was in a very good condition when it was returned",
        dateCreated: "Mar 17, 2026",
      },
    ],
    hostComments: [],
  },
];
